runtime: go
api_version: go1.8
service: benry-bot-go

handlers:
- url: /
  mime_type: text/html
  static_files: public/index.html
  upload: public/index.html

# All URLs are handled by the Go application script
- url: /.*
  script: _go_app

nobuild_files: vendor/
